version: '3'
services:
  some-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
  omblus-api:
    image: omblus-api:1.0
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=some-postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
volumes:
  postgres-data:
    driver: local